# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49d82f7079bef37ba513e775a0804c0e4e5eb3f59404561c5396f085dee37c4bb0f35bc19e22a61f02bfbf5454d969d74085078e1e164128081ff6203f044554

test:
  secret_key_base: eec7dcfa9f0983bf06ba1e0a943196d717f433e04ca5d29fd53e6b6e07e1c06342755b058ac494bc718986a34761a4b0dc234f61edb7a9498bde68cd9c8bf8e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
